image: python:3.6

before_script:
  - pip install poetry

stages:
  - test
  - publish
  - docs

test-py36:
  stage: test
  image: python:3.6
  script:
    - pip install tox
    - tox -e py36
  artifacts:
    reports:
      cobertura: coverage.xml
    expire_in: 15 days

test-py37:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox -e py37
  only:
    - web

test-py38:
  stage: test
  image: python:3.8
  script:
    - pip install tox
    - tox -e py38
  only:
    - web

publish:
  stage: publish
  script:
    - poetry config repositories.gitlab https://gitlab.inf.elte.hu/api/v4/projects/73/packages/pypi
    - poetry build
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  only:
    - web

docs:
  stage: docs
  script:
    - apt update
    - apt-get install libeigen3-dev
    - poetry install
    - cd docs
    - poetry run make html_all
  artifacts:
    paths:
      - docs/_build
    expire_in: 30 days
