image: python:3.6

before_script:
  - pip install poetry

stages:
  - test
  - build

unittest:
  variables:
    GIT_SUBMODULE_STRATEGY: none
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"'
  stage: test
  script:
    - pip install tox
    - tox

benchmark:
  variables:
    GIT_SUBMODULE_STRATEGY: normal #to use submodule
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"'
  stage: test
  script:
    - apt update
    - apt-get install libeigen3-dev
    - poetry install
    - cd pennylane/benchmark/
    - echo "Pennylane benchmark"
    - poetry run python benchmark.py -d default.qubit time bm_entangling_layers > ./output.txt
    - cd ../../
    - echo "Piquasso vs. StrawberryFields vacuum homodyne benchmark"
    - poetry run python benchmarks/vacuum_homodyne.py
  artifacts:
    paths:
      - pennylane/benchmark/output.txt
    expire_in: 15 days

generatewebpage: #`pages` kellene ha szeretnenk gitlab pages-t
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: none
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"'
  script:
    - apt update
    - apt-get install libeigen3-dev
    - poetry install
    - cd docs
    - poetry run make html_all
  artifacts:
    paths:
      - docs/_build
    expire_in: 30 days

buildpackage:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - poetry config repositories.gitlab https://gitlab.inf.elte.hu/api/v4/projects/73/packages/pypi
    - poetry build
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  only:
    - web
