image: python:3.6

variables:
  GIT_SUBMODULE_STRATEGY: normal #to use submodule

before_script:
  - pip install poetry

stages:
  - test
  - build

unittest:
  stage: test
  script:
    - pip install tox
    - tox

benchmark:
    stage: test
    script:
      - apt update
      - apt-get install libeigen3-dev
      - poetry install
      - cd pennylane/benchmark/
      - poetry run python benchmark.py -d default.qubit time bm_entangling_layers > ./output.txt
    artifacts:
      paths:
        - pennylane/benchmark/output.txt
      expire_in: 15 days


buildpackage:
  stage: build
  only: 
    - merge_requests
  script:
    - poetry config repositories.gitlab https://gitlab.inf.elte.hu/api/v4/projects/73/packages/pypi
    - poetry config pypi-token.gitlab 1z5AF-A6zsitDWpwGP91
    - poetry build
    - poetry publish -r gitlab

