[tool.poetry]
name = "piquasso"
version = "0.1.1"
description = ""
authors = ["Zoltán Kolarovszki"]
exclude = ["benchmarks"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.19.0"
flake8 = "^3.8.3"
quantum-blackbird = "^0.2.3"
BoSS-Tomev = "^0.0.6"
coverage = "^5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
strawberryfields = "^0.16.0"
pennylane = "^0.10.0"
pennylane-sf = "^0.9.0"
scipy = "^1.5.2"
recommonmark = "^0.6.0"
sphinx_rtd_theme = "^0.5.0"
llvmlite = "^0.33.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
