[tool.poetry]
name = "piquasso"
version = "0.1.3"
description = ""
authors = ["Zoltán Kolarovszki"]
exclude = ["benchmarks"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.19.0"
scipy = "^1.5.2"
quantum-blackbird = "^0.2.3"
BoSS-Tomev = "^0.0.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-profiling = "^1.7.0"
pytest-benchmark = "^3.2.3"
coverage = "^5.3"
flake8 = "^3.8.3"
strawberryfields = "^0.16.0"
recommonmark = "^0.6.0"
sphinx_rtd_theme = "^0.5.0"
llvmlite = "^0.33.0"
furo = "^2021.2.28-beta.28"
matplotlib = "^3.3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
