[tool.poetry]
name = "piquasso"
version = "0.1.0"
description = ""
authors = ["Zoltán Kolarovszki"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.19.0"
flake8 = "^3.8.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
strawberryfields = "^0.14.0"
pennylane = "^0.10.0"
pennylane-sf = "^0.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
